### ISSUE TITLE
Cannot read property 'Header' of undefined

### ISSUE THREAD

**Issue by quando12** [bTokman/yii2-react#2]
I have issue when I include layout.js 
Please help me
reactUi.js:29 Uncaught TypeError: Cannot read property 'Header' of undefined
    at index (reactUi.js:29)
    at Array.reduce (<anonymous>)
    at HTMLDocument.mountComponents (reactUi.js:34)

**Comment by bTokman** [comment]
Can u show me your layout js file where placed Header component?
